Feature/dtp 78 toolwindow
QSD-P1/VisualPatternAnalytics pull request #12
Opened 2022-12-27 20:08 UTC by StefanStrampel

Heb in de `DesignPatternWindowControl` het stuk laten staan die de clicks/expansion afhandelt zodat een ander het zo weer op kan pakken.

2022-12-27 21:44 UTC, SurfaceRabbit requested changes
Heb even vluchtig op mobiel naar de changes gekeken. Heb het nog niet getest. Zou je de comments willen checken? Thanks!

2022-12-27 21:44 UTC, SurfaceRabbit commented on src/VPA.Common.Adapters.Tests/RoslynAdapterTests.cs
> +				() => Assert.Equal(expected.GetType(), actual: result.GetType()),
Waarom is deze aangepast naar gettype i.p.v. name? Nu controleren we iets heel anders dan voorheen.

2022-12-27 21:44 UTC, SurfaceRabbit commented on src/VPA.Client.VisualStudio.Extension.VSIX/Adapters/IDetectorResultCollectionToTreeViewAdapter.cs
> +		 */
Deze comment zegt niet zoveel. Zou je deze kunnen aanpassen? Je kunt een ///<summary> gebruiken. Dit is wat bij c# gebruikt wordt voor comments buiten methoden vaak.

2022-12-27 21:44 UTC, SurfaceRabbit commented on src/VPA.Common.Adapters/VPA - Backup.Common.Adapters.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Wat is dit backup project?

2022-12-27 21:44 UTC, SurfaceRabbit commented on src/VPA.Common.Adapters/VPA.Common.Adapters.csproj
> +      <HintPath>..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\PresentationFramework.dll</HintPath>
Ik zie meerdere refs naar presentation zaken. Zijn deze benodigd in deze csproj?

2022-12-28 11:26 UTC, StefanStrampel commented on src/VPA.Common.Adapters/VPA - Backup.Common.Adapters.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
![image](https://user-images.githubusercontent.com/104631693/209805170-d1c6661c-b100-4cae-ae49-5d4b0d996148.png)

Ik zie die niet. Geen idee waar die weg komt 🤔

2022-12-29 16:14 UTC, SurfaceRabbit commented
![image](https://user-images.githubusercontent.com/51820925/209980007-4365d3c9-207e-4aa8-944c-d1c98485a3a1.png)

Joep en ik hadden fixes gedaan op deze branch zodat we donderdag avond iets werkend hadden. S.v.p. niet deze changes reverten.

2022-12-29 19:09 UTC, SurfaceRabbit approved these changes

2022-12-29 19:09 UTC, merged