DPT-83 Composite
QSD-P1/VisualPatternAnalytics pull request #18
Opened 2023-01-03 20:33 UTC by venraij

2023-01-03 21:54 UTC, SurfaceRabbit requested changes
Ik heb een paar comments geplaatst.
Verder voldoet de code niet aan de codeerstandaarden/afgesproken architectuur.

Zouden jullie daar naar willen kijken?

2023-01-03 21:54 UTC, SurfaceRabbit commented on src/VPA.Client.VisualStudio.Extension/ExampleAnalyzer.cs
> +			patternManager.UpdateTree(projectNode);
Waarom voeren we dit 2x achter elkaar uit??

2023-01-03 21:54 UTC, SurfaceRabbit commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			var config = DefaultConfiguration.GetInstance();
Ik zou hier mocking gebruiken i.p.v. de config. Je testen falen nu als er een bug zit in de config terwijl je testen daar niet voor bedoelt zijn. Dit geldt ook voor de andere testen

2023-01-03 21:54 UTC, SurfaceRabbit commented on src/VPA.Usecases/DetectionHelpers/ClassHelperUsecase.cs
> +		public static Dictionary<string, List<ClassNode>> GetClassesPerParentClass(ProjectNode projectNode)
Kunnen GetClassesPerParentClass en GetClassesPerInterface niet samengevoegd worden? Dit is bijna identiek aan elkaar

2023-01-03 21:54 UTC, SurfaceRabbit commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +			// Combine all classes per interface and abstract classes
Ik had zelf deze logica heel anders aangevlogen. I.P.V. dat je door alles heenloopt (meer dan 1x). Kun je ook loopen door de klassen die ontvangen worden. Zodra een klasse in de loop oogt als een composite klasse, dan kan je specifiek opzoek naar de interface en daarbijbehorende klasse.

Dit is denk ik performance efficienter, maar kijk zelf maar wat handig is.

2023-01-03 21:54 UTC, SurfaceRabbit commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +					var result = new DetectionResult($"{PatternName}_{resultCollection.Results.Count + 1}");
Zou dit zonder _ kunnen? Dat is hetzelfde als bij de singelton dan.

2023-01-03 21:54 UTC, SurfaceRabbit commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +		public async Task<DetectionResultCollection> Detect(ProjectNode projectNode)
Voorbeeld gepakt van refactoring guru, hij herkent het c# voorbeeld niet...

2023-01-03 22:01 UTC, venraij commented on src/VPA.Client.VisualStudio.Extension/ExampleAnalyzer.cs
> +			patternManager.UpdateTree(projectNode);
Waarschijnlijk een merge probleempje met develop geweest wordt gefixt

2023-01-03 22:03 UTC, venraij commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +		public async Task<DetectionResultCollection> Detect(ProjectNode projectNode)
PR staat nog in draft dit is al gefixt door stefan maar moet nog gepushed worden

2023-01-03 22:03 UTC, venraij commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +					var result = new DetectionResult($"{PatternName}_{resultCollection.Results.Count + 1}");
Yes wordt gefixt

2023-01-03 22:03 UTC, venraij commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			var config = DefaultConfiguration.GetInstance();
Eens

2023-01-03 22:05 UTC, venraij commented on src/VPA.Usecases/DetectionHelpers/ClassHelperUsecase.cs
> +		public static Dictionary<string, List<ClassNode>> GetClassesPerParentClass(ProjectNode projectNode)
Hebben wel beiden echt verschillende doelen, de ene zoekt de parent en de andere gebruikt interfaces. Interfaces hoeft niet gelijk te staan aan de parent of andersom. Maar ik begrijp dat het op elkaar lijkt qua logica.

2023-01-03 22:07 UTC, SurfaceRabbit commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +		public async Task<DetectionResultCollection> Detect(ProjectNode projectNode)
Als het draft is, waarom wordt dan gerequest voor review?

2023-01-03 22:11 UTC, venraij commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			var config = DefaultConfiguration.GetInstance();
Maar dat is nu ook verkeerd in de singleton dan

2023-01-03 22:13 UTC, SurfaceRabbit commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			var config = DefaultConfiguration.GetInstance();
Klopt, heb ik toen ook al benoemd

2023-01-03 22:15 UTC, SurfaceRabbit commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +		public async Task<DetectionResultCollection> Detect(ProjectNode projectNode)
https://refactoring.guru/design-patterns/proxy/csharp/example

2023-01-03 23:08 UTC, stijn-windesheim commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +			// Combine all classes per interface and abstract classes
Deze check hebben we op onze branch verplaatst naar de patternmanager. Dus mag van mij weg.

2023-01-04 20:01 UTC, StefanStrampel commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +			// Combine all classes per interface and abstract classes
Eens, dat zou efficienter zijn. Gaan we alleen niet meer reden deze sprint om dat nog om te gooien. Mijn voorstel is om het voor nu zo te laten en als bij het testen blijkt dat dit niet performed zoals we verwachten, dat we het dan aanpassen.

2023-01-04 20:02 UTC, StefanStrampel commented on src/VPA.Usecases/Detectors/DetectCompositeUsecase.cs
> +		public async Task<DetectionResultCollection> Detect(ProjectNode projectNode)
Ik heb dit voorbeeld net ook geprobeerd en hij wordt wel herkend. Kan het iets anders zijn aan jouw kant?

2023-01-05 07:30 UTC, joepvtl commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			_detectCompositeUsecase = detectCompositeUsecase;
Jo @venraij, dit is geen DI issue. Maar je kan niet zomaar dingen injecten in je tests zoals je hier doet. Je moet echt een nieuwe instantie maken. Zie: #20

2023-01-05 20:21 UTC, SurfaceRabbit commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			_detectCompositeUsecase = new(
Dit is niet hoe je zorgt dat je enkel de compositeUsecase test. Om enkel en alleen de CompositeUsecase te testen moet je de dependencies van de usecase mocken. We gebruiken bij andere testen daar de extensie Moq voor. Je kan dus afkijken hoe we dat bij andere testen doen

2023-01-05 20:24 UTC, venraij commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			_detectCompositeUsecase = new(
https://github.com/moq/moq4 @StefanStrampel

2023-01-05 20:29 UTC, SurfaceRabbit commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			_detectCompositeUsecase = new(
Excuus, staat niet in andere testen (zover ik snel zie i.v.m. dat daar geen dingen bij in geinject worden). Maar een veel gebruikte package is Moq https://github.com/moq/moq4

2023-01-05 20:33 UTC, StefanStrampel commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			_detectCompositeUsecase = new(
Zal ik zometeen naar kijken. Dit is nieuw voor mij op deze manier binnen C# :) 
De huidige manier van di werkt namelijk niet in de applicatie zonder interfaces dus ben dat ff aan het omzetten.

2023-01-06 08:20 UTC, SurfaceRabbit commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			_detectCompositeUsecase = new(
Wat heeft DI te maken  met mocken? Behalve dat je inderdaad een interface mockt

2023-01-06 08:37 UTC, StefanStrampel commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			_detectCompositeUsecase = new(
Niets, ik probeerde te vertellen dat ik dat nog aan het fixen was :)

2023-01-06 10:03 UTC, joepvtl commented on src/VPA.Usecases.Tests/DetectCompositeUsecaseTest.cs
> +			_detectCompositeUsecase = new(
Overlegd om dit voor nu zo te laten ivm tijd.

2023-01-06 10:04 UTC, joepvtl approved these changes

2023-01-06 10:19 UTC, merged

2023-01-06 10:19 UTC, joepvtl commented
Sorry hans maar we willen niet wachten:)