Feature/dpt 84 proxy pattern
QSD-P1/VisualPatternAnalytics pull request #19
Opened 2023-01-04 00:44 UTC by stijn-windesheim

- Added proxy pattern
- moved classnodes check to patternmanager
- Added interfacenodes to projectnode.
- added unit tests for proxy pattern
- Added OfTypeWithAccessModifier & OfTypeWithModifiers extension methods

2023-01-04 17:15 UTC, joepvtl requested changes

2023-01-04 17:15 UTC, joepvtl commented on src/VPA.Usecases/Detectors/ProxyDetectorUsecase.cs
> +				if (classNode.Interfaces != null && classNode.Children != null)
Dit kan je ook toevoegen aan de foreach. Dus project.ClassNodes.Where(hier je conditie). Dan wordt de code wat leesbaarder doordat die if weg kan.

2023-01-04 17:15 UTC, joepvtl commented on src/VPA.Usecases.Tests/ProxyDetectorUsecaseTests.cs
> +		static IProxyDetectorUsecase detector = config.GetService<IProxyDetectorUsecase>();
Zelfde als comment bij composite. We moeten niet de defaultconfiguration gebruiken bij tests. Maar we moeten zelf gwn de usecases maken. Dus new ProxyDetectorUsecase.

2023-01-04 17:15 UTC, joepvtl commented on src/VPA.Usecases/Interfaces/ISingletonDetectorUsecase.cs
> +	public interface ISingletonDetectorUsecase :IDetectorUsecase
De wijziging van deze naamgeving hebben we het vanavond maar weer over....

2023-01-04 17:15 UTC, joepvtl commented on src/VPA.Usecases/Managers/PatternManagerUsecase.cs
> +			if (projectNode.ClassNodes != null && projectNode.ClassNodes.Any(c => c.Children != null && c.Children.Any()))
Wat nou als hier wel interfaces zijn? Moet er om een designpattern te herkennen altijd een klasse zijn?

2023-01-04 18:36 UTC, stijn-windesheim commented on src/VPA.Usecases/Detectors/ProxyDetectorUsecase.cs
> +				if (classNode.Interfaces != null && classNode.Children != null)
Goeie.

2023-01-04 18:39 UTC, stijn-windesheim commented on src/VPA.Usecases/Managers/PatternManagerUsecase.cs
> +			if (projectNode.ClassNodes != null && projectNode.ClassNodes.Any(c => c.Children != null && c.Children.Any()))
De interfaces had ik pas op het laatst toegevoegd, dus niet aan gedacht om dat wellicht hier mee te nemen. Echter denk ik dat met alleen interfaces je geen design patterns kunt herkennen. Dus lijkt me overbodig.

2023-01-04 18:40 UTC, stijn-windesheim commented on src/VPA.Usecases.Tests/ProxyDetectorUsecaseTests.cs
> +		static IProxyDetectorUsecase detector = config.GetService<IProxyDetectorUsecase>();
Pas ik aan.

2023-01-05 07:36 UTC, joepvtl requested changes

2023-01-05 07:36 UTC, joepvtl commented on src/VPA.Usecases/DetectionHelpers/InterfaceHelper.cs
> +	public class InterfaceHelper
Jo, kan je deze nieuwe methode nog omzetten naar een usecase zoals afgesproken?

2023-01-05 07:36 UTC, joepvtl commented on src/VPA.Usecases/DetectionHelpers/FieldHelper.cs
> +		public static bool HasFoundOtherClassFromFieldType(IEnumerable<ClassNode> classNodes, FieldNode fieldNode, ClassNode classNode, out ClassNode? matchedResult)
Jo, kan je deze nieuwe methode nog omzetten naar een usecase zoals afgesproken? De bestaande methodes in deze helper pakken we op in de volgende sprint.

2023-01-06 10:43 UTC, joepvtl approved these changes

2023-01-06 11:07 UTC, joepvtl approved these changes

2023-01-06 11:07 UTC, merged