cleanup commented code
QSD-P1/VisualPatternAnalytics pull request #29
Opened 2023-01-21 19:20 UTC by stijn-windesheim

2023-01-21 19:22 UTC, stijn-windesheim commented on src/VPA.Common.Adapters/Adapters/Roslyn/RoslynAdapter.cs
> +			var treeNodes = tree.GetRoot().DescendantNodes();
Dit aangepast zodat descendentnodes niet 2 keer worden doorlopen.

2023-01-22 19:03 UTC, SurfaceRabbit requested changes
Ik wil zelf liever niet nu op de avond van oplevering nog wat commiten naar develop

2023-01-22 19:30 UTC, StefanStrampel commented
Met de groep besproken, geen changes meer zo vlak voor oplevering. 😄

2023-01-22 19:30 UTC, closed without merging

2023-01-22 20:41 UTC, stijn-windesheim commented
Ik zag het niet als echte "changes", aangezien het alleen om commentaarregels gingen, maar akkoord.