Dpt 75 generieke boom
QSD-P1/VisualPatternAnalytics pull request #8
Opened 2022-12-16 23:54 UTC by Gerke-v-W

2022-12-17 12:34 UTC, joepvtl requested changes

2022-12-17 12:34 UTC, joepvtl commented on src/VPA.Common.Adapters/Parser/Node.cs
> +	{
Hey @Gerke-v-W , Ik zou hier een abstracte classe van maken met de property List<Node> Nodes. Want alle nodes kunnen in theorie children hebben. Wat je nu hebt gedaan is dat je elke keer zelf opnieuw een property moet toevoegen, hierdoor ontstaat er dubbele code. Je kan ook de Location en Name property dan op deze klasse zetten.

2022-12-17 12:34 UTC, joepvtl commented on src/VPA.Common.Adapters/Parser/MethodObject.cs
> +		public string[] AccessModifiers = new string[6];
Hey ik zou hier een enum met  https://learn.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-7.0. Hierdoor hebben we typesafety en en kunnen we deze waardes hergebruiken.

2022-12-17 12:34 UTC, joepvtl commented on src/VPA.Common.Adapters/Parser/MethodObject.cs
> +		public string? ReturnType { get; set; }
Ik zou hier Type gebruiken. Dit kunnen we dan later inzetten om makkelijk te checken of het return type van een bepaalde classe is. Anders dan moeten we de class namen omzetten naar strings en dit zorgt voor extra code.

2022-12-17 12:34 UTC, joepvtl commented on src/VPA.Common.Adapters/Parser/ConstructorObject.cs
> +		public string[]? Parameters;
Ik zou voor de parameters ook Type gebruiken. Dit is het zelfde verhaal als bij de andere.

2022-12-17 12:34 UTC, joepvtl commented on src/VPA.Common.Adapters/Parser/ClassObject.cs
> +		public string? Abstraction { get; set; }
Kan je hier ook een Type? van maken? Zie andere comments voor meer info.

2022-12-17 12:34 UTC, joepvtl commented on src/VPA.Common.Adapters/Parser/ClassObject.cs
> +		public bool? Inherit { get; set; }
Wil je dit gebruiken voor of een classe interfaces implementeert? Dan zou ik eerder een Lijst met Type verwachten. Want nu kunnen we checken of hij iets inherit maar weten we niet wat.

2022-12-17 12:34 UTC, joepvtl commented on src/VPA.Common.Adapters/Parser/ClassObject.cs
> +		public bool? Inherit { get; set; }
Die bool? inherit kan dan weg

2022-12-17 12:34 UTC, joepvtl commented on src/VPA.Common.Adapters/Parser/FieldObject.cs
> +		public string? Type { get; set; }
Hier ook graag een Type gebruiken.

2022-12-17 13:13 UTC, SurfaceRabbit commented on src/VPA.Common.Adapters/Parser/MethodObject.cs
> +		public string? ReturnType { get; set; }
Maakt het wel logischer voor abstractie. We kunnen niet garanderen dat elke analyzer (bijvoorbeeld java) een type kan aanleveren. Ik zou dus wel een string gebruiken

2022-12-17 13:14 UTC, SurfaceRabbit commented on src/VPA.Common.Adapters/Parser/MethodObject.cs
> +		public string? ReturnType { get; set; }
Dit geldt ook voor de overige comments over type

2022-12-17 13:16 UTC, SurfaceRabbit commented
Ik denk dat deze bestanden op de verkeerde plek staan. Deze classen zijn de core van onze applicatie en zouden dus ook centraal moeten staan. Volgens de architectuur die we hebben beschreven in het SAD zouden deze dus in het domain moeten zitten. De adapter bevindt zich aan de buitenlaag van de applicatie en zou absoluut niet de core modellen van de applicatie moeten bevatten.

2022-12-17 13:36 UTC, SurfaceRabbit commented on src/VPA.Common.Adapters/Parser/ClassObject.cs
> +	public class ClassObject: Node
Ik zou de naamgeving anders doen en het ook nodes noemen i.p.v. objecten. Maakt het in de code duidelijker wat het is

2022-12-17 14:41 UTC, Gerke-v-W commented on src/VPA.Common.Adapters/Parser/MethodObject.cs
> +		public string? ReturnType { get; set; }
Ik heb dit in eerste instantie geprobeerd. Maar inderdaad met het oog op andere talen besloten om toch de string te gebruiken om het los te koppelen van C#. Daarom heb ik alles terug gezet naar strings.

2022-12-17 14:45 UTC, Gerke-v-W commented on src/VPA.Common.Adapters/Parser/ClassObject.cs
> +		public bool? Inherit { get; set; }
Mijn idee was hier dat je hiermee kan checken of een klasse uberhaupt een andere klasse implementeerd. Is dit niet het geval, dan valt hij voor veel design patterns al af als onderdeel van een design pattern. Ik weet niet of dit een mogelijkheid is, maar het lijkt mij een snelle manier van uitsluiting.

De lijst met classes die geïmplementeerd worden mist inderdaad nog.

2022-12-17 14:52 UTC, Gerke-v-W commented on src/VPA.Common.Adapters/Parser/Node.cs
> +	{
Gedaan, ik heb alleen naam erin gezet. Ik had er niks in gezet om alle mogelijkheden open te laten voor wat voor soort nodes dan ook. Als een Node totaal anders is, moet het niet noodgedwongen waardes hebben. Ik denk dat bijvoorbeeld een project node geen locatie heeft.

2022-12-17 14:55 UTC, Gerke-v-W commented on src/VPA.Common.Adapters/Parser/ConstructorObject.cs
> +		public string? Name { get; set; }
Scherp opgemerkt, volgens mij nu aangepast

2022-12-17 15:24 UTC, stijn-windesheim commented on src/VPA.Common.Adapters/Parser/ProjectObject.cs
> +		public List<Node> nodes;
Maak je van deze list ook nog een property van?

2022-12-17 16:01 UTC, stijn-windesheim commented on src/VPA.Common.Adapters/Parser/ConstructorObject.cs
> +		public string? Name { get; set; }
Ik mis dit nog steeds op sommige plekken. Wellicht heb je de aanpassingen nog niet ingecheckt.

2022-12-17 16:34 UTC, Gerke-v-W commented on src/VPA.Common.Adapters/Parser/MethodObject.cs
> +		public string[] AccessModifiers = new string[6];
Done.

Als ik het goed begrijp uit de link die jij stuurde kan je door middel van de FlagAttribute ervoor zorgen dat er combinaties mogelijk zijn. Ik denk dat het zo goed is gedaan, maar zeker ben ik hier niet van.

2022-12-17 16:49 UTC, Gerke-v-W commented on src/VPA.Common.Adapters/Parser/ConstructorObject.cs
> +		public string? Name { get; set; }
Ik dacht dat een getter en setter voor een array niet zinvol zou zijn. 
De getter kan ik nog wel inkomen.
Maar een setter weet ik niet zo goed hoe dat in de praktijk zou werken 😄
Misschien een add functionaliteit ofzo.

2022-12-17 20:49 UTC, stijn-windesheim commented on src/VPA.Common.Adapters/Parser/ConstructorObject.cs
> +		public string? Name { get; set; }
Een setter voor een array, betekend dat je de array compleet mag overschrijven bijv SomeCollection = new Array(). Nou is dit niet altijd wenselijk, dus als je dit wilt afschermen, dan zou ik alleen de getter definieren. Ik zie het als best-practice om van alle publieke velden properties te maken. Check ook dit bijv: https://stackoverflow.com/questions/3069901/properties-vs-fields-need-help-grasping-the-uses-of-properties-over-fields

2022-12-17 21:08 UTC, stijn-windesheim requested changes

2022-12-17 21:08 UTC, stijn-windesheim commented on src/VPA.Domain/Parser/AccessModifier.cs
> +		@public = 0,
Nog een aantal opmerkingen mbt deze enum:

1. Ik zie dit eerder als een soort 'SyntaxKind' enum, dan als accessmodifier.
2. Ik zou bij elke waarde uit de enum ipv @[naam], dit aanpassen naar [Naam]Keyword (Beginnend met hoofdleet)
3. Accessmodifier kan alleen private, public, protected, of internal zijn.

2022-12-17 21:21 UTC, stijn-windesheim commented on src/VPA.Common.Adapters/Parser/Node.cs
> +	{
Ik zou de List<Node> ook een niveau omhoogtrekken, maar dan een abstracte class bijv CollectionNode ertussen zetten, waarin project/class van overerven ipv Node. Dus CollectionNode zal dan de property List<Node> bevatten en daarnaast ook van Node overerven.

2022-12-18 18:26 UTC, SurfaceRabbit commented on src/VPA.Common.Adapters/Parser/ClassObject.cs
> +	public class ClassObject: Node
Ik zie dat je de rename hebt gedaan @Gerke-v-W. Echter heten de bestanden nog naar de oude naam

2022-12-19 09:59 UTC, stijn-windesheim approved these changes

2022-12-19 16:49 UTC, merged